version: '2.4'
services:
  web:
    build:
      context: .
    image: shipment_tracker
    command: >
      sh -c 'bundle exec rake db:structure:load && \
             exec bundle exec unicorn --config-file config/unicorn.rb'
    environment: &common_environment
      DATABASE_URL: postgresql://postgres:postgres@postgres/shipment_tracker
      HONEYBADGER_ENV: development
      HONEYBADGER_REPORT_DATA: 'true'
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      PROTECT_STDOUT: 'true'
      PROMETHEUS_EXPORTER_HOST: prometheus-exporter
      PROMETHEUS_EXPORTER_PORT: 9394
      RAILS_ENV: "${RAILS_ENV:-production}"
    environment:
      <<: *common_environment
      AUTH0_CLIENT_ID: Y9ltgcdXUkNA4hRDWuP0nxDaZVdIskBM
      AUTH0_CONNECTION: fundingcircle.com
      AUTH0_DOMAIN: fundingcircle.auth0.com
      GIT_REPOSITORY_CACHE_DIR: /tmp/git
      JIRA_FQDN: http://jira:8080
      JIRA_PASSWD: shipment_tracker
      JIRA_PATH: ''
      JIRA_USER: shipment_tracker
      JIRA_USE_SSL: 'false'
      PORT_HTTP: 1201
      SECRET_KEY_BASE: "$SECRET_KEY_BASE"
      SSH_PRIVATE_KEY:
      SSH_USER: git
      UNICORN_TIMEOUT: 3600
    env_file: secrets.env
    tty: true
    stdin_open: true
    ports:
      - 127.0.0.1:1201-1202:1201
    depends_on:
      prometheus-exporter:
        condition: service_healthy
      postgres:
        condition: service_healthy
      jira:
        condition: service_started
    volumes:
      - git:/tmp/git
    healthcheck:
      test: curl localhost:1201/healthcheck
      interval: 10s
    scale: 2

  git-worker:
    image: shipment_tracker
    command: bundle exec rake jobs:update_git_loop
    environment:
      <<: *common_environment
      GIT_REPOSITORY_CACHE_DIR: /tmp/git
      SSH_PRIVATE_KEY:
      SSH_USER: git
    env_file: secrets.env
    tty: true
    stdin_open: true
    user: root
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - git:/tmp/git

  event-worker:
    image: shipment_tracker
    command: bundle exec rake jobs:update_events_loop
    environment:
      <<: *common_environment
    env_file: secrets.env
    tty: true
    stdin_open: true
    depends_on:
      web:
        condition: service_healthy

  delayed-job:
    image: shipment_tracker
    command: bundle exec rake jobs:work
    environment:
      <<: *common_environment
    env_file: secrets.env
    tty: true
    stdin_open: true
    depends_on:
      prometheus-exporter:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: bundle exec rake jobs:check
      interval: 10s

  prometheus-exporter:
    image: shipment_tracker
    command: bundle exec prometheus_exporter
    env_file: secrets.env
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -f localhost:9394/send-metrics
      interval: 10s
    ports:
      - 127.0.0.1:9394:9394

  postgres:
    image: postgres:9.6-alpine
    command: postgres -c log_statement=all
    environment:
      POSTGRES_DB: shipment_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --host=localhost --dbname=shipment_tracker --username=postgres || exit 1
      interval: 10s
    ports:
      - 127.0.0.1:5532:5432

  jira:
    image: dchevell/jira-core
    volumes:
      - jira:/var/atlassian/application-data/jira
    ports:
      - 127.0.0.1:8080:8080

volumes:
  pgdata:
  git:
  jira:
